### ISSUE TITLE
Пустой ответ от graphouse если отстуствуют данные за указанный период

### ISSUE THREAD

**Issue by AlexZzz** [yandex/graphouse#35]
Используем связку graphite-web(1.0.2) + graphouse(1.3) + grafana.
При попытке получить данные по нескольким серверам за определенный промежуток времени, если данных по одному из серверов за это время нет, grafana выдает ошибку:
`&#10;<center>&#10;<h2>&#10;<p>Graphite encountered an unexpected error while handling your request.</p>&#10;<p>Please contact your site administrator if the problem persists.</p>&#10;</h2>&#10;<br>&#10;<div>&#10;&#10;</div>&#10;&#10;<div>&#10;<pre>Traceback (most recent call last):&#10;  File &#34;/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 149, in get_response&#10;    response = self.process_exception_by_middleware(e, request)&#10;  File &#34;/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 147, in get_response&#10;    response = wrapped_callback(request, *callback_args, **callback_kwargs)&#10;  File &#34;/opt/graphite/local/lib/python2.7/site-packages/graphite/render/views.py&#34;, line 174, in renderView&#10;    del series[0]&#10;IndexError: list assignment index out of range&#10;&#10;</pre>&#10;</div>&#10;&#10;</center>&#10;`
При этом, если попытаться получить данные за период, в течении которого данные по всем серверам есть, хотя бы частично то ошибки не возникает. Например, если данные начали появляться сегодня, то график за последние 3 дня ошибки не выдаст. Однако, график за "вчера" построить не удастся.
Если запросить данные из graphouse за период, пересекающийся с периодом когда данные начали поступать в graphouse:
`curl  'http://localhost:2005/metricData?metrics=collectd.srv6.nstat-IpOutNoRoutes.gauge&start=1502020061&reqKey=empty&end=1502117769' `
Ответ будет следующим:
`{"collectd.srv6.nstat-IpOutNoRoutes.gauge":{"start":1502020020,"end":1502117700,"step":60,"points":[null,null,null,null,null,null,null,null,null,null,null,null,null,...,null,null,null,null,null,null,70.0,70.0,...,70.0]}}`
Если же уменьшить время в поле `end`, то graphouse возвращает пустое значение:
`curl  'http://localhost:2005/metricData?metrics=collectd.srv6.nstat-IpOutNoRoutes.gauge&start=1502020061&reqKey=empty&end=1502031061'
{}`
Если график строить в graphite-web, то он перестает отображать графики как только в выборку попадает сервер, данные с которого за весь указанный период отсутствуют.

**Comment by AndreevDm** [comment]
Fixed
