### ISSUE TITLE
Question regarding retention

### ISSUE THREAD

**Issue by mamoep** [yandex/graphouse#67]
I am evaluating the usage of graphouse and I am struggling with the retention. As far as I understand the retention-config you configure a start point for a specific precision but there is no endpoint. So how will old data ever be deleted from the database?

**Comment by AndreevDm** [comment]
Hi. To clean old data you can use `ALTER TABLE [db.]table DROP PARTITION 'name'` command in ClickHouse.

https://clickhouse.yandex/docs/en/single/#manipulations-with-partitions-and-parts


Graphouse don't do it now, but you can create an issue.

**Comment by mamoep** [comment]
Thanks, I will do that
