### ISSUE TITLE
Levrage BalancedClickhouseDataSource  from JDBC to spread the Metric Traffic Load

### ISSUE THREAD

**Issue by meshpaul** [yandex/graphouse#70]
Guys,

  Do you have any plans to use [BalancedClickhouseDataSource  ](https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/BalancedClickhouseDataSource.java
)  Thus if telemetry data lives in Distributed, Replicated and Sharded Cluster the load will get spread evenly and guarantee HA if one of CH servers is down in a cluster.

**Comment by AndreevDm** [comment]
Looks like usefull and simple feature https://github.com/yandex/graphouse/pull/71

**Comment by AndreevDm** [comment]
Version 1.10

Documentation - https://github.com/yandex/graphouse/blob/master/doc/config.md#clickhouse-connection
